// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, feed_id, title, url, description, created_at, updated_at, published_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, title, url, description, feed_id, created_at, updated_at, published_at
`

type CreatePostParams struct {
	ID          uuid.UUID
	FeedID      uuid.UUID
	Title       string
	Url         string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PublishedAt time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.FeedID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getPostByUser = `-- name: GetPostByUser :many
SELECT p.id, p.title, p.url, p.description, p.feed_id, p.created_at, p.updated_at, p.published_at, f.id, f.name, f.url, f.user_id, f.created_at, f.updated_at, f.last_fetched_at, u.id, u.name, u.created_at, u.updated_at
FROM posts AS p
JOIN feeds as f ON p.feed_id = f.id
JOIN users as u ON f.user_id = u.id
WHERE u.name = ($1)
ORDER BY p.published_at DESC
LIMIT $2
`

type GetPostByUserParams struct {
	Name  string
	Limit int32
}

type GetPostByUserRow struct {
	ID            uuid.UUID
	Title         string
	Url           string
	Description   sql.NullString
	FeedID        uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	PublishedAt   time.Time
	ID_2          uuid.UUID
	Name          string
	Url_2         string
	UserID        uuid.UUID
	CreatedAt_2   time.Time
	UpdatedAt_2   time.Time
	LastFetchedAt sql.NullTime
	ID_3          uuid.UUID
	Name_2        string
	CreatedAt_3   time.Time
	UpdatedAt_3   time.Time
}

func (q *Queries) GetPostByUser(ctx context.Context, arg GetPostByUserParams) ([]GetPostByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostByUser, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostByUserRow
	for rows.Next() {
		var i GetPostByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.FeedID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.ID_2,
			&i.Name,
			&i.Url_2,
			&i.UserID,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.LastFetchedAt,
			&i.ID_3,
			&i.Name_2,
			&i.CreatedAt_3,
			&i.UpdatedAt_3,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
